name: Check markdown links
on: 
  - push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Mixed HTTP/HTTPS Check
        run: |
          ./.github/workflows/mixed_http_check.sh

      - name: Dead Link Checker
        uses: peter-evans/link-checker@v1.2.2
        with:
          # Note that this uses Liche args: https://github.com/raviqqe/liche
          args: --timeout 60 index.html aboutme.md contact.md projects.md resume.md

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3.0.0
        with:
          title: Link Checker Report
          content-filepath: ./link-checker/out.md
          labels: bug, automated issue
